In [3]:
import os
import numpy as np 
print(np.linspace(0,9,1))
def test(orientx, orienty, orientz):

    R = np.vstack([orientx, orienty, orientz]).T
    R = np.linalg.inv(R)

    tet = np.array([0.5, 0.25, 0])

    tet = tet @ R
    
    print(tet)

    tet = (tet + 2) % 1
    
    print(tet)

[0.]


In [4]:

''' Use for 100 surface '''
orientx = [1, 0, 0]
orienty = [0, 1, 0]
orientz = [0 ,0, 1]
test(orientx, orienty, orientz)

''' Use for 110 surface '''
orientx = [1, 1, 0]
orienty = [0, 0,-1]
orientz = [-1,1, 0]
test(orientx, orienty, orientz)

''' Use for 111 surface '''
orientx = [1, 1, 1]
orienty = [-1,2,-1]
orientz = [-1,0, 1]
test(orientx, orienty, orientz)

[0.5  0.25 0.  ]
[0.5  0.25 0.  ]
[ 0.25  0.25 -0.25]
[0.25 0.25 0.75]
[0.125 0.25  0.125]
[0.125 0.25  0.125]


In [ ]:


np.round(x,3) >= np.round(y, 3)