In [15]:
import os
import numpy as np 
import glob
def test(orientx, orienty, orientz):

    R = np.vstack([orientx, orienty, orientz]).T
    R = np.linalg.inv(R)

    tet = np.array([0.5, 0.25, 0])

    tet = tet @ R
    
    # print(tet)

    tet = (tet + 2) % 1
    
    print(tet)

folder_path = '../../Lammps_Dump/Surface/'

folder_paths = glob.glob(os.path.join(folder_path,'111','New_Depth_*.data'))
print(sorted(['neb1', 'neb0', 'neb8']))

string = 'bulk/text'
print(string.split('/')[-2])

x = [[1, 2], [3, 4, 5]]

np.hstack(x).reshape(-1, 1)

['neb0', 'neb1', 'neb8']
bulk


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:

''' Use for 100 surface '''
orientx = [1, 0, 0]
orienty = [0, 1, 0]
orientz = [0 ,0, 1]
test(orientx, orienty, orientz)

''' Use for 110 surface '''
orientx = [1, 1, 0]
orienty = [0, 0,-1]
orientz = [-1,1, 0]
test(orientx, orienty, orientz)

''' Use for 111 surface '''
orientx = [1, 1, 1]
orienty = [-1,2,-1]
orientz = [-1,0, 1]
test(orientx, orienty, orientz)

[0.5  0.25 0.  ]
[0.25 0.25 0.75]
[0.125 0.25  0.125]


In [5]:
data = {'txt':{'a':4}, 'txt2':{'b':5}}

for d in data:
    print(d)
    for k in data[d]:
        print(data[d][k])

txt
4
txt2
5
